### ISSUE TITLE
Doesn't work with internal keyboard

### ISSUE THREAD

**Issue by zodiacg** [tekezo/Seil#30]
I'm sure I have changed the modifier setting to "No Action", but it still doesn't work on my internal keyboard. All hacks including "Other keys" have no effect.
But PCKeyboardHack works fine with my wireless keyboard which is recognized as "USB Receiver". 
Any idea on how to fix this?

**Comment by keeprock** [comment]
@zodiacg do you have any success this your hackintosh and remapping? I've got same problem here.

**Comment by zodiacg** [comment]
@keeprock In the VoodooPS2Controller.kext I used, I could remap the capslock key to hyper key by modifying a plist file. I couldn't remember correctly as it was years ago, and I'm using Linux instead of hackintosh now. You can check your VoodooPS2Controller.kext and have a try.
