### ISSUE TITLE
Can't remap CapsLock on Non-Mac keyboard

### ISSUE THREAD

**Issue by lungelimb** [tekezo/Seil#39]
Using latest Seil @ 10.9.3 Hackintosh-book (No DSDT, only Clover patches applied on boot if that matters). Tried to remap to 79,80 keycodes and such, but no success actually. EventViewer doesn't shows anything on caps after I set 'no action' in prefs.

**Comment by keeprock** [comment]
@lungelimb do you have any success with PS2?
