### ISSUE TITLE
How to map CapsLock as Escape AND Ctrl

### ISSUE THREAD

**Issue by lmartins** [tekezo/Seil#46]
My goal was to map CapsLock to Escape if pressed by itself and to Control if pressed in combination with another keys. I've heard somewhere this was possible to achieve with Seil but Im not able to figure it out. 

Could you help please?

**Comment by tekezo** [comment]
You should use Karabiner.
https://pqrs.org/osx/karabiner/index.html.en

Change your caps lock key to control from System Preferences > Keyboard > Modifier Keys.
Then enable this setting in Karabiner Preferences.

![screen shot 2015-04-20 at 10 44 35 pm](https://cloud.githubusercontent.com/assets/659178/7231224/1b066e5c-e7af-11e4-962f-43403130ef86.png)

(If you do not want to change the physical left control key, let me know.)

**Comment by lmartins** [comment]
Brilliant, that was it. Thanks.
