### ISSUE TITLE
Changing of a language not on each key pressing

### ISSUE THREAD

**Issue by Seg-mel** [tekezo/Seil#50]
From time to time the app not changes a language if quickly press on CAPS LOCK. How to solve this problem? Why is this happening? (Latest Mac OS X)

**Comment by tekezo** [comment]
If you did not do "No Action" configuration, the caps lock key is delayed.
Did you do "No Action" setting?
https://pqrs.org/osx/karabiner/seil.html.en#usage

**Comment by Seg-mel** [comment]
@tekezo Oh, thanks! I installed the app before buying a usb keyboard and set the app for keyboard of a notebook=) Thanks again!
