### ISSUE TITLE
Erratic keyboard behaviour in Yosemite

### ISSUE THREAD

**Issue by patspam** [tekezo/Seil#51]
Ever since upgrading to Yosemite I've been seeing some bizarre keyboard behaviour (typically after using Cmd+Tab to switch between workspaces), and I think I've traced it back to Seil.

Often, if I start typing immediately after using Cmd+Tab to switch between workspaces, the first few characters of text gets repeated over and over as fast as the keyboard can send it.

Also, if I Cmd+Tab from one app into Chrome and then hit Cmd+W to close the active tab, the entire Chrome app closes instead.

Both of these issues go away after uninstalling Seil.

My Seil config is very basic - I only use it to remap CAPS Lock to Esc.

**Comment by tekezo** [comment]
I never faced such problem.
Are there any log messages related with Seil (or common error messages) in system.log?
You can confirm system.log in Console.app.
https://pqrs.org/osx/karabiner/faq.html.en#general
