### ISSUE TITLE
May not work with El Capitan

### ISSUE THREAD

**Issue by Grafz** [tekezo/Seil#52]
I've set the caps lock key to 53 and rebooted but it doesn't seem to work. (never had problems with Yosemite)

<img width="451" alt="screenshot" src="https://cloud.githubusercontent.com/assets/12874704/8639334/a94eddf8-28a4-11e5-9a57-efa1e9d3bebf.png">

<img width="257" alt="screenshot" src="https://cloud.githubusercontent.com/assets/12874704/8639337/bbbd9074-28a4-11e5-980b-cfc6442b2413.png">

<img width="683" alt="screenshot" src="https://cloud.githubusercontent.com/assets/12874704/8639329/8dc38be2-28a4-11e5-80cc-f03147d20dfe.png">

**Comment by tekezo** [comment]
Are you using the latest stable version? (v11.2.0)
You can confirm Seil version in "Misc & Uninstall" tab.

**Comment by Grafz** [comment]
Yup.

<img width="633" alt="screenshot" src="https://cloud.githubusercontent.com/assets/12874704/8663979/2ca068a2-299f-11e5-87eb-f786a91f6343.png">

**Comment by tekezo** [comment]
I cannot reproduce this issue.
Please reinstall Seil, then restart your system.

If your issue still happen, please confirm this issue in a clean environment like Guest User.

**Comment by Grafz** [comment]
It seems to work now. I restarted in a different partition and when I came back to start tests in the El Capitan partition it seems to work. Sorry for what looks like a false alarm.
