### ISSUE TITLE
"Command + Option" Modifier Doesn't Work in Finder

### ISSUE THREAD

**Issue by dreamfliper** [tekezo/Seil#65]
I configured my Right Command as Right Option, and I use last version which can run on 10.10.
In Safari and Termianl, this combination modifier does work.  For example, "Command + Option + W" will close other tabs except current tab.
When I try to use "Command + Option + V" to do something like "cut and post", it doesn't work. I need to use my left command and left option ,which are not configured by Seil, to achieve that.

**Comment by tekezo** [comment]
It's hardware limitation "2-key rollover".
https://pqrs.org/osx/karabiner/faq.html.en#rollover
Please continue using your left command key.
