### ISSUE TITLE
Seil cannot connect with kernel extension in macOS 10.12 DP 1

### ISSUE THREAD

**Issue by heshiyou** [tekezo/Seil#69]
![image](https://cloud.githubusercontent.com/assets/707533/16047335/450aa014-3282-11e6-854e-3ba3839c7df8.png)

Seil version: 12.1.0/12.1.2

**Comment by nguyenquangminh0711** [comment]
I have that problem too. Seil allows to config keys but it doesn't have any effects.

**Comment by neilio** [comment]
Dupe of #68
