### ISSUE TITLE
Hyper Key hack in MacOS 10.12 Sierra using Karabiner-Elements and Keyboard Maestro

### ISSUE THREAD

**Issue by digiltd** [tekezo/Seil#73]
The Hyper Key and all of the many things I use it for is the reason I am not upgrading just yet.

[Brett Terpstra](http://brettterpstra.com/2016/09/26/web-excursions-for-september-26-2016/) posted a link to a solution using Keyboard Maestro 

http://imgur.com/a/Pz0hk

Works quite well

**Comment by scottming** [comment]
I think [Hammerspoon](http://www.hammerspoon.org/go/) can do it better.

**Comment by digiltd** [comment]
Thanks, just reading about that now

https://github.com/lodestone/hyper-hacks
